### ISSUE TITLE
'Update Profile' functionality not working

### ISSUE THREAD

**Issue by adragione** [nelsynelz/Tact_Issues#5]
**Describe the bug**
When trying to update profile information from the 'My Profile' page, none of the data entered in the text fields actually gets saved to the profile. Navigating away from the page after clicking on the 'UPDATE PROFILE' button results in a blank profile page.  Also, during the registration process there is a BIO section that is filled out, I believe that should be saved during registration and pre-populate on the 'My Profile' page to avoid having users enter it twice.

**To Reproduce**
1. Go to 'My Profile' page after registering/logging in
2. Update any of the text fields (such as First/Last Name or About Me)
3. Click on 'UPDATE PROFILE'
4. Navigate away from the page and click back into 'My Profile'

**Expected behavior**
As with other prompts during registration, a confirmation message should appear to indicate a successful save of changes to the profile data and then retain that data when existing the 'My Profile' page.

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 75.0.3770.142

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: iOS 12.1.2
 - Browser: Safari

**Additional context**
I'm sure that this is a simple fix and just a matter of pointing the 'UPDATE PROFILE' button to an action that updates the users profile information in the respective DynamoDB table. Caching the BIO response during the registration process to pre-populate this on the profile page will probably require a slightly different change to fix, but that should also be a relatively easy thing to achieve.

**Comment by danwritecode** [comment]
Completed!
