### ISSUE TITLE
Issue with Deal Process ( Individual) - Completion Proof Step

### ISSUE THREAD

**Issue by adragione** [nelsynelz/Tact_Issues#7]
**Describe the bug**
When clicking on the 'VIEW' button to review the deal as it's in the 'Completion Proof' step, I am unable to bring up the view in the UI on the Individual side of the deal.  While the UI does not present an error and just shows an empty rectangle with the 'Review Deal' title, the console shows the following error message:

vue.runtime.esm.js:1888 TypeError: Cannot read property 'streamShoutout' of undefined
    at s.lr (UserDeals_DealOverlay.vue?80d5:1)
    at s.e._render (vue.runtime.esm.js:3542)
    at s.n (vue.runtime.esm.js:4060)
    at tn.get (vue.runtime.esm.js:4473)
    at tn.run (vue.runtime.esm.js:4548)
    at $r (vue.runtime.esm.js:4304)
    at Array.<anonymous> (vue.runtime.esm.js:1980)
    at ct (vue.runtime.esm.js:1906)

I am able to view the deal at this step from the Org perspective without any issues, but there are no other actions than to simply view the deal details as this step waits for input from the Individual.

**To Reproduce**
1. Log in as TeamLiquid/password and view adella6's profile
2. Click on the green 'Proposal Deal' button and go through the flow
3. In this instance, I create a StreamShoutout deal-type
4. Accept the deal from the Individual's perspective
5. Go to 'My Deals' page and try to view the deal that is now Active
6. See the error message in the console of the Chrome developers tools (F12)

**Expected behavior**
At this step in the deal process, the Individual should be able to view the deal details and upload proof of completion of the engagement with the Org/Sponsor.

**Screenshots**
![image](https://user-images.githubusercontent.com/47489313/63229215-2a610000-c1cc-11e9-9bda-e86894ba0767.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional
 - Browser: Google Chrome
 - Version: 76.0.3809.100

**Comment by danwritecode** [comment]
Issue was happening because frontend was setting the Deal Completion object that the API was returning equal to the object that was being rendered in the front end. The problem was the Deal Completion object is undefined until completion proof is actually written to the deal. Added a new method that checks first if this object was returned from the DB. If it wasn't it doesn't set the front end object, if it was it sets the object to be rendered equal to the object returned from the DB. All good!
